#!/usr/bin/env python3
"""
Add the full-width "Cited in peer-reviewed research" panel above the footer on
every page that carries a Bioz badge, and stop the badge asserting numbers it
cannot keep current.

Why this exists
---------------
The hero badges hardcoded both the citation count and a five-solid-star rating.
Both drifted: the `940` badge read 30, 31 and 42 on different pages for the same
slug, `577` read 159 against a catalogue value of 162, and the five stars were
fixed decoration regardless of the real Bioz Stars score (Model 577 is 95/100).
The live widget is now the single source of truth, so nothing can contradict
itself again.

Safe to re-run. Every edit is marker-guarded and idempotent.

    python3 _shared/inject-bioz-cited.py            # apply to the whole site
    python3 _shared/inject-bioz-cited.py --dry-run  # report only
    python3 _shared/inject-bioz-cited.py --revert   # remove panel, keep badges
    python3 _shared/inject-bioz-cited.py FILE...    # limit to given pages
"""

import argparse
import os
import re
import sys

WIDGET = "https://www.bioz.com/v_widget_6_0/13441/"

START = "<!-- BIOZ-CITED-STRIP start (generated by _shared/inject-bioz-cited.py) -->"
END = "<!-- BIOZ-CITED-STRIP end -->"
CSS_ID = "bioz-cited-css"
JS_SRC = "/_shared/bioz-cited.js"

CSS = """<style id="%s">
.bioz-cited{background:linear-gradient(180deg,#f6f8fb 0%%,#eef2f7 100%%);border-top:1px solid #dfe6ef;padding:44px 0 52px}
.bioz-cited-inner{max-width:1180px;margin:0 auto;padding:0 22px}
.bioz-cited-head{display:flex;align-items:flex-start;gap:16px;flex-wrap:wrap;margin-bottom:20px}
.bioz-cited-mark{flex:0 0 auto;display:inline-flex;align-items:center;justify-content:center;background:#113163;color:#fff;font:700 12px/1 Arial,Helvetica,sans-serif;letter-spacing:.14em;padding:9px 12px;border-radius:5px;margin-top:3px}
.bioz-cited-head h2{margin:0 0 4px;font:700 22px/1.25 "Myriad Pro",Arial,Helvetica,sans-serif;color:#113163}
.bioz-cited-head p{margin:0;font:400 14px/1.55 Arial,Helvetica,sans-serif;color:#5a6472;max-width:68ch}
.bioz-cited-ext{margin-left:auto;align-self:center;font:700 13px Arial,Helvetica,sans-serif;color:#0655a3;text-decoration:none;white-space:nowrap;border-bottom:1px solid rgba(6,85,163,.35)}
.bioz-cited-ext:hover{border-bottom-color:#0655a3}
.bioz-cited-frame{position:relative;background:#fff;border:1px solid #dbe3ec;border-radius:8px;box-shadow:0 2px 10px -4px rgba(17,49,99,.18);overflow:hidden;min-height:520px}
.bioz-cited-frame object{display:block;width:100%%;height:560px;border:0}
.bioz-cited-ph{display:flex;align-items:center;justify-content:center;height:520px;color:#8a94a3;font:400 14px Arial,Helvetica,sans-serif}
@media (max-width:720px){
  .bioz-cited{padding:32px 0 38px}
  .bioz-cited-head h2{font-size:19px}
  .bioz-cited-ext{margin-left:0}
  .bioz-cited-frame object,.bioz-cited-ph{height:640px}
  .bioz-cited-frame{min-height:640px}
}
@media print{.bioz-cited{display:none}}
</style>
""" % CSS_ID

PANEL = """%s
<section id="bioz-cited" class="bioz-cited" aria-labelledby="bioz-cited-h">
 <div class="bioz-cited-inner">
  <div class="bioz-cited-head">
   <span class="bioz-cited-mark">BIOZ</span>
   <div>
    <h2 id="bioz-cited-h">Cited in peer-reviewed research</h2>
    <p>Independent publications citing this instrument, indexed by Bioz. Citation
    counts and Bioz Stars ratings are shown live and update as new papers are indexed.</p>
   </div>
   <a class="bioz-cited-ext" href="{url}" target="_blank" rel="noopener">Open on Bioz &rarr;</a>
  </div>
  <div class="bioz-cited-frame" data-bioz-src="{url}">
   <div class="bioz-cited-ph">Loading peer-reviewed citations&hellip;</div>
  </div>
 </div>
</section>
%s
""" % (START, END)

# Both badge variants: the white hero card on datasheets/manuals, and the purple
# .btn-bioz button on index/home pages. Both carry class="bioz-badge".
STARS_RE = re.compile(
    r'<span[^>]*(?:class="bz-stars"|line-height:0)[^>]*>\s*(?:<svg\b.*?</svg>\s*)+</span>',
    re.S | re.I,
)
COUNT_RE = re.compile(
    r'Cited in\s*<b[^>]*>\s*[\d,]+\s*</b>\s*peer-reviewed publications', re.I
)
SLUG_RE = re.compile(re.escape(WIDGET) + r"([A-Za-z0-9_.\-]+)")


def find_pages(root):
    skip = {".git", ".claude", "node_modules", "books"}
    out = []
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in dirnames if d not in skip]
        for fn in filenames:
            if fn.endswith(".html"):
                out.append(os.path.join(dirpath, fn))
    return sorted(out)


def transform(text):
    """Return (new_text, notes). Idempotent."""
    notes = []
    m = SLUG_RE.search(text)
    if not m:
        return text, notes
    url = WIDGET + m.group(1)

    # 1. Strip the fabricated five-star rating from every badge variant.
    text, n = STARS_RE.subn("", text)
    if n:
        notes.append("removed %d hardcoded star block(s)" % n)

    # 2. Stop asserting a citation count the page cannot keep current.
    text, n = COUNT_RE.subn("Cited in peer-reviewed research", text)
    if n:
        notes.append("dropped %d static count(s)" % n)

    # 3. Head CSS, once.
    if CSS_ID not in text:
        if "</head>" not in text:
            return text, notes + ["SKIPPED: no </head>"]
        text = text.replace("</head>", CSS + "</head>", 1)
        notes.append("added panel CSS")

    # 4. The panel itself, above the footer.
    if START not in text:
        panel = PANEL.format(url=url)
        if "</main>" in text:
            text = text.replace("</main>", panel + "</main>", 1)
            notes.append("inserted panel before </main>")
        else:
            fm = re.search(r'<footer\b[^>]*class="[^"]*gfoot', text)
            if not fm:
                return text, notes + ["SKIPPED: no </main> or <footer class=gfoot>"]
            text = text[: fm.start()] + panel + text[fm.start():]
            notes.append("inserted panel before <footer>")

    # 5. Hydration script, once, last thing before </body>.
    if JS_SRC not in text:
        if "</body>" not in text:
            return text, notes + ["SKIPPED: no </body>"]
        text = text.replace(
            "</body>", '<script src="%s" defer></script>\n</body>' % JS_SRC, 1
        )
        notes.append("added hydration script")

    return text, notes


def revert(text):
    notes = []
    new = re.sub(re.escape(START) + r".*?" + re.escape(END) + r"\n?", "", text, flags=re.S)
    if new != text:
        notes.append("removed panel")
        text = new
    new = re.sub(r'<style id="%s">.*?</style>\n?' % CSS_ID, "", text, flags=re.S)
    if new != text:
        notes.append("removed CSS")
        text = new
    new = text.replace('<script src="%s" defer></script>\n' % JS_SRC, "")
    if new != text:
        notes.append("removed script tag")
        text = new
    return text, notes


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("files", nargs="*")
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--revert", action="store_true")
    args = ap.parse_args()

    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    targets = [os.path.abspath(f) for f in args.files] or find_pages(root)

    changed = skipped = untouched = 0
    for path in targets:
        try:
            with open(path, encoding="utf-8") as fh:
                original = fh.read()
        except (OSError, UnicodeDecodeError) as exc:
            print("  !! %s: %s" % (os.path.relpath(path, root), exc))
            continue

        if WIDGET not in original and START not in original:
            continue

        new, notes = revert(original) if args.revert else transform(original)

        if any(n.startswith("SKIPPED") for n in notes):
            skipped += 1
            print("  SKIP %s -- %s" % (os.path.relpath(path, root), "; ".join(notes)))
            continue
        if new == original:
            untouched += 1
            continue

        changed += 1
        print("  %-58s %s" % (os.path.relpath(path, root), "; ".join(notes)))
        if not args.dry_run:
            with open(path, "w", encoding="utf-8") as fh:
                fh.write(new)

    print("\n%s: %d changed, %d already current, %d skipped"
          % ("DRY RUN" if args.dry_run else "applied", changed, untouched, skipped))
    return 1 if skipped else 0


if __name__ == "__main__":
    sys.exit(main())
