#!/usr/bin/env python3
"""
Video accessibility pass.

What the audit actually found, once the media was inspected rather than counted:

  * 8 of the 9 self-hosted <video> elements are the "materialize" product
    animations. Parsing the MP4 atoms shows a `vide` track and NO `soun` track:
    they are completely silent. WCAG 1.2.2 (Captions, Prerecorded) applies to
    synchronized media with audio, so captions do not apply to these at all.
    Each also sits beside an <img class="real"> that already carries descriptive
    alt text for the same product, so they add no information of their own.
    Correct treatment is to mark them decorative, not to caption them.

  * icx-weather-promo.mp4 is the one self-hosted file with a `soun` track. It is
    left untouched here: writing a caption file without knowing what the audio
    contains would mean inventing content, which is worse than the gap.

  * The real spoken-word content is on YouTube. Only 4 distinct videos are
    embedded sitewide. Two of them are long webinars (57 and 46 minutes) for
    which we already hold real time-coded transcripts in video-search-index.json.
    Those get an on-page, keyboard-accessible transcript under the player, which
    is a genuine 1.2.2/1.2.3 improvement and needs no third-party player API.

Transcript text is YouTube auto-caption output. It is reproduced as written, with
sentence capitalisation only. Nothing is reworded, summarised or invented, and
the panel says plainly that it is auto-generated.

Safe to re-run; every edit is marker-guarded.

    python3 _shared/inject-video-a11y.py --dry-run
    python3 _shared/inject-video-a11y.py
"""

import argparse
import json
import os
import re
import sys

START = "<!-- VIDEO-TRANSCRIPT start (generated by _shared/inject-video-a11y.py) -->"
END = "<!-- VIDEO-TRANSCRIPT end -->"
CSS_ID = "video-a11y-css"

# Silent decorative animations. Verified: MP4 has a `vide` track and no `soun`.
SILENT_DECORATIVE = re.compile(
    r'(<video\b(?![^>]*\baria-hidden\s*=)[^>]*\bclass\s*=\s*["\'][^"\']*\bmat\b[^"\']*["\'][^>]*?)(\s*/?>)',
    re.I,
)

CSS = """<style id="%s">
.vt-wrap{margin:14px 0 4px}
.vt-wrap>summary{cursor:pointer;font:700 14px Arial,Helvetica,sans-serif;color:#0655a3;
  padding:9px 12px;background:#f4f7fa;border:1px solid #dbe3ec;border-radius:6px;list-style:none;display:flex;
  align-items:center;gap:8px}
.vt-wrap>summary::-webkit-details-marker{display:none}
.vt-wrap>summary::before{content:"\\25B8";display:inline-block;transition:transform .15s;font-size:12px}
.vt-wrap[open]>summary::before{transform:rotate(90deg)}
.vt-wrap>summary:hover{background:#eaf0f7}
.vt-note{font:400 12.5px/1.5 Arial,Helvetica,sans-serif;color:#5a6472;margin:10px 2px 6px}
.vt-body{max-height:460px;overflow-y:auto;border:1px solid #dbe3ec;border-top:0;
  border-radius:0 0 6px 6px;padding:14px 16px;background:#fff}
.vt-body p{margin:0 0 12px;font:400 14px/1.65 Arial,Helvetica,sans-serif;color:#22303c}
.vt-body a.vt-t{display:inline-block;min-width:52px;font:700 12px/1.65 Arial,Helvetica,sans-serif;
  color:#0655a3;text-decoration:none;border-bottom:1px solid rgba(6,85,163,.3);margin-right:8px}
.vt-body a.vt-t:hover{border-bottom-color:#0655a3}
@media print{.vt-wrap{display:none}}
</style>
""" % CSS_ID


def sentence_case(text):
    """Capitalise sentence starts. Formatting only; no words are changed."""
    text = text.strip()
    if not text:
        return text
    out = []
    cap = True
    for ch in text:
        if cap and ch.isalpha():
            out.append(ch.upper())
            cap = False
        else:
            out.append(ch)
        # "]" covers auto-caption sound cues such as "[Music]" / "[Applause]",
        # after which the next word starts a fresh sentence.
        if ch in ".!?]":
            cap = True
    s = "".join(out)
    # Standalone "i" -> "I"
    return re.sub(r"\bi\b", "I", s)


def hhmmss(sec):
    sec = int(sec)
    h, m, s = sec // 3600, (sec % 3600) // 60, sec % 60
    return ("%d:%02d:%02d" % (h, m, s)) if h else ("%d:%02d" % (m, s))


def build_transcript(vid, video, group_seconds=45):
    """Group raw caption segments into readable timestamped paragraphs."""
    segs = video.get("seg") or []
    if not segs:
        return None
    paras, cur, cur_start = [], [], None
    for t, txt in segs:
        if cur_start is None:
            cur_start = t
        cur.append(txt.strip())
        if t - cur_start >= group_seconds:
            paras.append((cur_start, " ".join(cur)))
            cur, cur_start = [], None
    if cur:
        paras.append((cur_start or 0, " ".join(cur)))

    rows = []
    for start, body in paras:
        url = "https://www.youtube.com/watch?v=%s&amp;t=%ds" % (vid, int(start))
        rows.append(
            '<p><a class="vt-t" href="%s" target="_blank" rel="noopener">%s</a>%s</p>'
            % (url, hhmmss(start), sentence_case(body))
        )

    title = video.get("title", "").replace("&", "&amp;").replace("<", "&lt;")
    return (
        '%s\n<details class="vt-wrap" id="transcript-%s">\n'
        '<summary>Transcript &mdash; %s</summary>\n'
        '<div class="vt-body">\n'
        '<p class="vt-note">Auto-generated transcript, reproduced as spoken and lightly '
        'formatted for reading. Timestamps open the video at that point. If you need a '
        'corrected transcript, contact us at '
        '<a href="mailto:info@berkeleynucleonics.com">info@berkeleynucleonics.com</a>.</p>\n'
        "%s\n</div>\n</details>\n%s\n"
        % (START, vid, title, "\n".join(rows), END)
    )


def find_embed_end(s, vid):
    """End offset of the element wrapping this video's embed, for insertion."""
    m = re.search(r"youtube(?:-nocookie)?\.com/embed/" + re.escape(vid), s)
    if not m:
        return None
    # Close of the <iframe ...> tag, then walk out of any immediate wrapper div.
    close = s.find(">", m.end())
    if close == -1:
        return None
    tail = s[close: close + 400]
    m2 = re.match(r">\s*</iframe>\s*(</div>)?", tail, re.I)
    if m2:
        return close + m2.end()
    return close + 1


def process(path, index, dry):
    with open(path, encoding="utf-8", errors="replace") as fh:
        original = fh.read()
    s = original
    notes = []

    # 1. Mark the silent decorative animations.
    s, n = SILENT_DECORATIVE.subn(r'\1 aria-hidden="true"\2', s)
    if n:
        notes.append("%d decorative video" % n)

    # 2. On-page transcripts for embedded YouTube videos we hold transcripts for.
    added = 0
    for vid, video in index.items():
        if not video.get("seg"):
            continue
        if ("embed/" + vid) not in s:
            continue
        if ("transcript-" + vid) in s:
            continue
        block = build_transcript(vid, video)
        if not block:
            continue
        pos = find_embed_end(s, vid)
        if pos is None:
            continue
        s = s[:pos] + "\n" + block + s[pos:]
        added += 1
    if added:
        notes.append("%d transcript" % added)

    if added and CSS_ID not in s and "</head>" in s:
        s = s.replace("</head>", CSS + "</head>", 1)
        notes.append("css")

    if s == original:
        return None
    if not dry:
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(s)
    return "; ".join(notes)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    with open(os.path.join(root, "video-search-index.json"), encoding="utf-8") as fh:
        index = {v["id"]: v for v in json.load(fh)["videos"]}

    skip = {".git", ".claude", "node_modules", "books"}
    changed = 0
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in dirnames if d not in skip]
        for fn in sorted(filenames):
            if not fn.endswith(".html"):
                continue
            path = os.path.join(dirpath, fn)
            res = process(path, index, args.dry_run)
            if res:
                changed += 1
                print("  %-52s %s" % (os.path.relpath(path, root), res))
    print("\n%s: %d file(s) changed" % ("DRY RUN" if args.dry_run else "applied", changed))
    return 0


if __name__ == "__main__":
    sys.exit(main())
