#!/usr/bin/env python3
"""
Add the full-width "Cited in peer-reviewed research" panel above the footer on
every page that carries a Bioz badge, and stop the badge asserting numbers it
cannot keep current.

Why this exists
---------------
The hero badges hardcoded both the citation count and a five-solid-star rating.
Both drifted: the `940` badge read 30, 31 and 42 on different pages for the same
slug, `577` read 159 against a catalogue value of 162, and the five stars were
fixed decoration regardless of the real Bioz Stars score (Model 577 is 95/100).
The live widget is now the single source of truth, so nothing can contradict
itself again.

Safe to re-run. Every edit is marker-guarded and idempotent.

    python3 _shared/inject-bioz-cited.py            # apply to the whole site
    python3 _shared/inject-bioz-cited.py --dry-run  # report only
    python3 _shared/inject-bioz-cited.py --revert   # remove panel, keep badges
    python3 _shared/inject-bioz-cited.py FILE...    # limit to given pages
"""

import argparse
import os
import re
import sys

WIDGET = "https://www.bioz.com/v_widget_6_0/13441/"

START = "<!-- BIOZ-CITED-STRIP start (generated by _shared/inject-bioz-cited.py) -->"
END = "<!-- BIOZ-CITED-STRIP end -->"
CSS_ID = "bioz-cited-css"
JS_SRC = "/_shared/bioz-cited.js"

CSS = """<style id="%s">
.bioz-cited{background:linear-gradient(180deg,#0a1626 0%%,#0e2038 100%%);padding:18px 0 22px}
.bioz-cited-inner{max-width:1180px;margin:0 auto;padding:0 22px}
.bioz-cited-head{display:flex;align-items:flex-start;gap:12px;flex-wrap:wrap;margin-bottom:10px}
.bioz-cited-mark{flex:0 0 auto;display:inline-flex;align-items:center;justify-content:center;background:linear-gradient(115deg,#4c1d95 0%%,#6d28d9 58%%,#7c3aed 100%%);color:#fff;font:700 10px/1 Arial,Helvetica,sans-serif;letter-spacing:.14em;padding:7px 10px;border-radius:5px;margin-top:1px;box-shadow:0 4px 14px -6px rgba(124,58,237,.6)}
.bioz-cited-head h2{margin:0 0 2px;font:700 17px/1.25 "Myriad Pro",Arial,Helvetica,sans-serif;color:#fff}
.bioz-cited-head p{margin:0;font:400 12px/1.45 Arial,Helvetica,sans-serif;color:#9fb3d0;max-width:78ch}
.bioz-cited-ext{margin-left:auto;align-self:center;font:700 12px Arial,Helvetica,sans-serif;color:#7cc4ff;text-decoration:none;white-space:nowrap;border-bottom:1px solid rgba(124,196,255,.35)}
.bioz-cited-ext:hover{border-bottom-color:#7cc4ff}
.bioz-cited-frame{position:relative;height:400px;background:linear-gradient(180deg,#fbfcfe 0%%,#eef3f9 100%%);border:1px solid rgba(124,170,220,.28);border-radius:12px;box-shadow:0 14px 36px -16px rgba(2,8,20,.6);overflow:hidden;transition:height .45s ease}
.bioz-cited-frame::before{content:"";position:absolute;top:0;left:0;right:0;height:3px;background:linear-gradient(90deg,#7c3aed 0%%,#37b6f0 100%%);z-index:1}
.bioz-cited-frame object{display:block;width:118%%;height:474px;border:0;transform:scale(.847);transform-origin:0 0;transition:height .45s ease}
.bioz-cited-fade{position:absolute;left:0;right:0;bottom:0;height:40px;background:linear-gradient(180deg,rgba(238,243,249,0) 0%%,#eef3f9 88%%);pointer-events:none;transition:opacity .3s ease}
.bioz-cited.is-open .bioz-cited-frame{height:585px}
.bioz-cited.is-open .bioz-cited-frame object{height:691px}
.bioz-cited.is-open .bioz-cited-fade{opacity:0}
.bioz-cited-ph{display:flex;align-items:center;justify-content:center;height:100%%;color:#8a94a3;font:400 13px Arial,Helvetica,sans-serif}
.bioz-cited-foot{display:flex;justify-content:center;margin-top:10px}
.bioz-cited-more{display:inline-flex;align-items:center;gap:7px;background:none;border:1px solid rgba(124,196,255,.4);border-radius:999px;color:#9fc7ef;font:700 10.5px/1 "Myriad Pro",Arial,Helvetica,sans-serif;letter-spacing:.08em;text-transform:uppercase;padding:7px 14px;cursor:pointer;transition:background .2s ease,border-color .2s ease,color .2s ease}
.bioz-cited-more:hover{background:rgba(55,182,240,.12);border-color:#37b6f0;color:#fff}
.bioz-cited-more svg{transition:transform .3s ease}
.bioz-cited.is-open .bioz-cited-more svg{transform:rotate(180deg)}
@media (max-width:720px){
  .bioz-cited{padding:16px 0 20px}
  .bioz-cited-head h2{font-size:16px}
  .bioz-cited-ext{margin-left:0}
  .bioz-cited-frame{height:540px}
  .bioz-cited-frame object{width:100%%;height:540px;transform:none}
  .bioz-cited.is-open .bioz-cited-frame{height:1040px}
  .bioz-cited.is-open .bioz-cited-frame object{height:1040px}
}
@media print{.bioz-cited{display:none}}
</style>
""" % CSS_ID

PANEL = """%s
<section id="bioz-cited" class="bioz-cited" aria-labelledby="bioz-cited-h">
 <div class="bioz-cited-inner">
  <div class="bioz-cited-head">
   <span class="bioz-cited-mark">BIOZ</span>
   <div>
    <h2 id="bioz-cited-h">Cited in peer-reviewed research</h2>
    <p>Independent publications citing this instrument, indexed by Bioz. Citation
    counts and Bioz Stars ratings are shown live and update as new papers are indexed.</p>
   </div>
   <a class="bioz-cited-ext" href="{url}" target="_blank" rel="noopener">Open on Bioz &rarr;</a>
  </div>
  <div class="bioz-cited-frame" data-bioz-src="{url}">
   <div class="bioz-cited-ph">Loading peer-reviewed citations&hellip;</div>
   <div class="bioz-cited-fade" aria-hidden="true"></div>
  </div>
  <div class="bioz-cited-foot">
   <button class="bioz-cited-more" type="button" aria-expanded="false" aria-controls="bioz-cited">
    <span data-more>Show full listings</span><span data-less hidden>Collapse</span>
    <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><polyline points="6 9 12 15 18 9"/></svg>
   </button>
  </div>
 </div>
</section>
%s
""" % (START, END)

# Both badge variants: the white hero card on datasheets/manuals, and the purple
# .btn-bioz button on index/home pages. Both carry class="bioz-badge".
STARS_RE = re.compile(
    r'<span[^>]*(?:class="bz-stars"|line-height:0)[^>]*>\s*(?:<svg\b.*?</svg>\s*)+</span>',
    re.S | re.I,
)
COUNT_RE = re.compile(
    r'Cited in\s*<b[^>]*>\s*[\d,]+\s*</b>\s*peer-reviewed publications', re.I
)
SLUG_RE = re.compile(re.escape(WIDGET) + r"([A-Za-z0-9_.\-]+)")


def find_pages(root):
    skip = {".git", ".claude", "node_modules", "books"}
    out = []
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in dirnames if d not in skip]
        for fn in filenames:
            if fn.endswith(".html"):
                out.append(os.path.join(dirpath, fn))
    return sorted(out)


def transform(text):
    """Return (new_text, notes). Idempotent."""
    notes = []
    m = SLUG_RE.search(text)
    if not m:
        return text, notes
    url = WIDGET + m.group(1)

    # 1. Strip the fabricated five-star rating from every badge variant.
    text, n = STARS_RE.subn("", text)
    if n:
        notes.append("removed %d hardcoded star block(s)" % n)

    # 2. Stop asserting a citation count the page cannot keep current.
    text, n = COUNT_RE.subn("Cited in peer-reviewed research", text)
    if n:
        notes.append("dropped %d static count(s)" % n)

    # 3. Head CSS, once.
    if CSS_ID not in text:
        if "</head>" not in text:
            return text, notes + ["SKIPPED: no </head>"]
        text = text.replace("</head>", CSS + "</head>", 1)
        notes.append("added panel CSS")

    # 4. The panel itself, above the footer.
    if START not in text:
        panel = PANEL.format(url=url)
        if "</main>" in text:
            text = text.replace("</main>", panel + "</main>", 1)
            notes.append("inserted panel before </main>")
        else:
            fm = re.search(r'<footer\b[^>]*class="[^"]*gfoot', text)
            if not fm:
                return text, notes + ["SKIPPED: no </main> or <footer class=gfoot>"]
            text = text[: fm.start()] + panel + text[fm.start():]
            notes.append("inserted panel before <footer>")

    # 5. Hydration script, once, last thing before </body>.
    if JS_SRC not in text:
        if "</body>" not in text:
            return text, notes + ["SKIPPED: no </body>"]
        text = text.replace(
            "</body>", '<script src="%s" defer></script>\n</body>' % JS_SRC, 1
        )
        notes.append("added hydration script")

    return text, notes


def revert(text):
    notes = []
    new = re.sub(re.escape(START) + r".*?" + re.escape(END) + r"\n?", "", text, flags=re.S)
    if new != text:
        notes.append("removed panel")
        text = new
    new = re.sub(r'<style id="%s">.*?</style>\n?' % CSS_ID, "", text, flags=re.S)
    if new != text:
        notes.append("removed CSS")
        text = new
    new = text.replace('<script src="%s" defer></script>\n' % JS_SRC, "")
    if new != text:
        notes.append("removed script tag")
        text = new
    return text, notes


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("files", nargs="*")
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--revert", action="store_true")
    args = ap.parse_args()

    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    targets = [os.path.abspath(f) for f in args.files] or find_pages(root)

    changed = skipped = untouched = 0
    for path in targets:
        try:
            with open(path, encoding="utf-8") as fh:
                original = fh.read()
        except (OSError, UnicodeDecodeError) as exc:
            print("  !! %s: %s" % (os.path.relpath(path, root), exc))
            continue

        if WIDGET not in original and START not in original:
            continue

        new, notes = revert(original) if args.revert else transform(original)

        if any(n.startswith("SKIPPED") for n in notes):
            skipped += 1
            print("  SKIP %s -- %s" % (os.path.relpath(path, root), "; ".join(notes)))
            continue
        if new == original:
            untouched += 1
            continue

        changed += 1
        print("  %-58s %s" % (os.path.relpath(path, root), "; ".join(notes)))
        if not args.dry_run:
            with open(path, "w", encoding="utf-8") as fh:
                fh.write(new)

    print("\n%s: %d changed, %d already current, %d skipped"
          % ("DRY RUN" if args.dry_run else "applied", changed, untouched, skipped))
    return 1 if skipped else 0


if __name__ == "__main__":
    sys.exit(main())
